import type { Metric } from "../types/dataset.ts";

export const metrics: Metric[] = [
  {
    id: "population-total",
    slug: "population-total",
    label: "Total population",
    shortLabel: "Population",
    domain: "population",
    summary: "Headline population estimates for Canada and provinces.",
    geographyLevels: ["country", "province"],
    timeGrain: "quarterly",
    unit: "people",
    taxonomyNodeId: "population-total",
    sourceIds: ["statscan-pop-estimates"],
    methodologyId: "official-release",
    estimateEnabled: true,
    topicTags: ["population", "headline"]
  },
  {
    id: "population-canadian-born",
    slug: "population-canadian-born",
    label: "Canadian-born citizens",
    shortLabel: "Canadian-born",
    domain: "population",
    summary: "Residents born in Canada and holding citizenship by birth.",
    geographyLevels: ["country", "province"],
    timeGrain: "quarterly",
    unit: "people",
    taxonomyNodeId: "canadian-born",
    sourceIds: ["statscan-pop-estimates"],
    methodologyId: "official-release",
    estimateEnabled: true,
    topicTags: ["population", "residency-status"]
  },
  {
    id: "population-naturalized",
    slug: "population-naturalized",
    label: "Naturalized citizens",
    shortLabel: "Naturalized",
    domain: "population",
    summary: "Residents who immigrated and later became Canadian citizens.",
    geographyLevels: ["country", "province"],
    timeGrain: "quarterly",
    unit: "people",
    taxonomyNodeId: "naturalized",
    sourceIds: ["statscan-pop-estimates"],
    methodologyId: "official-release",
    estimateEnabled: true,
    topicTags: ["population", "residency-status"]
  },
  {
    id: "population-permanent-residents",
    slug: "population-permanent-residents",
    label: "Non-citizen permanent residents",
    shortLabel: "Permanent residents",
    domain: "population",
    summary: "Residents with permanent resident status who are not citizens.",
    geographyLevels: ["country", "province"],
    timeGrain: "quarterly",
    unit: "people",
    taxonomyNodeId: "permanent-residents",
    sourceIds: ["statscan-pop-estimates"],
    methodologyId: "official-release",
    estimateEnabled: true,
    topicTags: ["population", "residency-status"]
  },
  {
    id: "population-temporary-residents",
    slug: "population-temporary-residents",
    label: "Temporary residents",
    shortLabel: "Temporary residents",
    domain: "population",
    summary: "Residents with temporary status, including work, study, mobility, and asylum streams.",
    geographyLevels: ["country", "province"],
    timeGrain: "quarterly",
    unit: "people",
    taxonomyNodeId: "temporary-residents",
    sourceIds: ["statscan-pop-estimates", "ircc-temp-residents"],
    methodologyId: "official-release",
    estimateEnabled: true,
    topicTags: ["population", "residency-status"]
  },
  {
    id: "temporary-asylum-claimants",
    slug: "temporary-asylum-claimants",
    label: "Asylum claimants",
    shortLabel: "Asylum claimants",
    domain: "population",
    summary: "Temporary residents with asylum claimant status where available.",
    geographyLevels: ["country", "province"],
    timeGrain: "quarterly",
    unit: "people",
    taxonomyNodeId: "temp-asylum",
    sourceIds: ["ircc-temp-residents"],
    methodologyId: "official-release",
    estimateEnabled: true,
    topicTags: ["temporary-residents", "asylum"]
  },
  {
    id: "temporary-tfw",
    slug: "temporary-tfw",
    label: "Temporary Foreign Worker Program",
    shortLabel: "TFW",
    domain: "population",
    summary: "Temporary residents admitted under Temporary Foreign Worker Program streams.",
    geographyLevels: ["country", "province"],
    timeGrain: "quarterly",
    unit: "people",
    taxonomyNodeId: "temp-tfw",
    sourceIds: ["ircc-temp-residents"],
    methodologyId: "official-release",
    estimateEnabled: true,
    topicTags: ["temporary-residents", "workers"]
  },
  {
    id: "temporary-imp",
    slug: "temporary-imp",
    label: "International Mobility Program",
    shortLabel: "IMP",
    domain: "population",
    summary: "Temporary residents admitted under International Mobility Program work permit streams.",
    geographyLevels: ["country", "province"],
    timeGrain: "quarterly",
    unit: "people",
    taxonomyNodeId: "temp-imp",
    sourceIds: ["ircc-temp-residents"],
    methodologyId: "official-release",
    estimateEnabled: true,
    topicTags: ["temporary-residents", "workers"]
  },
  {
    id: "temporary-students",
    slug: "temporary-students",
    label: "Study permit holders",
    shortLabel: "Students",
    domain: "population",
    summary: "Temporary residents present under study permit streams.",
    geographyLevels: ["country", "province"],
    timeGrain: "quarterly",
    unit: "people",
    taxonomyNodeId: "temp-student",
    sourceIds: ["ircc-temp-residents"],
    methodologyId: "official-release",
    estimateEnabled: true,
    topicTags: ["temporary-residents", "students"]
  }
];
